# Generated by Django 2.2.7 on 2019-11-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191124_0329'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('profile', 'product')},
        ),
    ]
