# Generated by Django 2.2.7 on 2019-11-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191124_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivery', 'Delivery'), ('finished', 'Finished')], default='pending', max_length=30),
            preserve_default=False,
        ),
    ]
