# Generated by Django 2.2.7 on 2019-11-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191124_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='subtotal',
        ),
    ]
