# Generated by Django 2.2.7 on 2019-11-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_index'], 'verbose_name_plural': 'categories'},
        ),
    ]
