# Generated by Django 2.2.7 on 2019-11-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191123_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_from_ldap',
        ),
    ]
